CREATE TABLE "User"."Users" (
	"Id" text NOT NULL,
	"UserPassword" varchar(100) NULL,
	"UserName" varchar(256) NULL,
	"NormalizedUserName" varchar(256) NULL,
	"Email" varchar(256) NULL,
	"NormalizedEmail" varchar(256) NULL,
	"EmailConfirmed" bool NOT NULL,
	"PasswordHash" text NULL,
	"SecurityStamp" text NULL,
	"ConcurrencyStamp" text NULL,
	"PhoneNumber" text NULL,
	"PhoneNumberConfirmed" bool NOT NULL,
	"TwoFactorEnabled" bool NOT NULL,
	"LockoutEnd" timestamptz NULL,
	"LockoutEnabled" bool NOT NULL,
	"AccessFailedCount" int4 NOT NULL,
	"AboutInfo" text NULL,
	"Age" int4 NOT NULL DEFAULT 0,
	"City" varchar(200) NULL,
	"DateRegister" timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
	"FirstName" varchar(100) NULL,
	"Patronymic" varchar(100) NULL,
	"Plan" varchar(10) NULL,
	"UserIcon" text NULL,
	"UserRole" varchar(1) NULL DEFAULT ''::character varying,
	"LastName" varchar(100) NULL,
	"Gender" varchar(1) NULL DEFAULT ''::character varying,
	"RememberMe" bool NOT NULL DEFAULT false,
	"ExecutorSpecializations" jsonb NULL,
	"IsSuccessedTest" bool NULL,
	"TaskTemplates" jsonb NULL DEFAULT '[]'::jsonb,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
CREATE INDEX "EmailIndex" ON "User"."Users" USING btree ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "User"."Users" USING btree ("NormalizedUserName");